server:
  port: 8080
---
spring:
  application:
    name: API-Gateway
  config:
    activate:
      on-profile: prod
eshop:
  host-names:
    customers: customers
    products: products
    orders: orders