kind: Service
apiVersion: v1
metadata:
  name: customers
spec:
  selector:
    app: customers
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: eshop/customers-service:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
